### ISSUE TITLE
Implementing cdk-nag in tests files

### ISSUE THREAD

**Issue by msaavedra-earnd** [cdklabs/cdk-nag#1278]
### General Issue

Guidance on cdk-nag implementation for test files

### The Question

I am currently implementing cdk-nag using Typescript and to implement the pipeline **tests**, I am getting the error of:
```
Suppression path "/this/construct/path" did not match any resource. This can occur when a resource does not exist or if a suppression is applied before a resource is created.
```

```
 FAIL  test/pipeline.test.ts (78.874 s)
  ● PipelineStack › Check AWS pipeline default

    Suppression path "/this/construct/path" did not match any resource. This can occur when a resource does not exist or if a suppression is applied before a resource is created.

      155 |     pipeline.buildPipeline();
      156 |     // The path suppression will error if you comment out "ExamplePipeline.buildPipeline();""
    > 157 |     NagSuppressions.addResourceSuppressionsByPath(this, '/this/construct/path', [
          |                     ^
      158 |       {
      159 |         id: 'AwsSolutions-IAM5',
      160 |         reason: 'Policy created by CDK to allow cross-account access and CB projects rights',

      at node_modules/cdk-nag/src/nag-suppressions.ts:115:15
          at Array.forEach (<anonymous>)
      at Function.addResourceSuppressionsByPath (node_modules/cdk-nag/src/nag-suppressions.ts:98:15)
      at new PipelineStack (src/pipeline-stack.ts:157:21)
      at Object.<anonymous> (test/pipeline.test.ts:9:27)
```

This is my **pipeline.test.ts** so far:
```
describe('Check cdk-nag AwsSolutions Pack', () => {
  let pipelineStack: PipelineStack;
  let app: App;
  // In this case we can use beforeAll() over beforeEach() since our tests 
  // do not modify the state of the application 
  beforeAll(() => {
    // GIVEN
    app = new App();
    pipelineStack = new PipelineStack(app, "PipelineStack", {
      env: {
        account: "123456789012",
        region: "us-east-2",
      },
    });
    // WHEN
    Aspects.of(pipelineStack).add(new AwsSolutionsChecks());

    NagSuppressions.addResourceSuppressionsByPath(pipelineStack, '/this/construct/path', [
      {
        id: 'AwsSolutions-IAM5',
        reason: 'Policy created by CDK to allow cross-account access and CB projects rights',
      },
    ]);
  });

  // THEN
  test('No unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(pipelineStack).findWarning(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*')
    );
    expect(warnings).toHaveLength(0);
  });

  test('No unsuppressed Errors', () => {
    const errors = Annotations.fromStack(pipelineStack).findError(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*')
    );
    expect(errors).toHaveLength(0);
  });
});
```

In my pipeline stack for Codepipeline I already added `ExamplePipeline.buildPipeline()` to force the creation of the resources first, but for the tests, how could this be done/implemented?

### cdk-nag version

v2.26.11

### Language

Typescript

**Comment by dontirun** [comment]
What's the exact path for `/this/construct/path`?

 What does the suppression exactly look like?

From what I can see in the error message something in the path doesn't match

**Comment by msaavedra-earnd** [comment]
So, this is my **pipeline-stack.ts**:
```
import { Stack, StackProps } from "aws-cdk-lib";
import {
  LinuxBuildImage,
  BuildEnvironmentVariableType,
  Cache,
  LocalCacheMode,
  BuildSpec,
} from "aws-cdk-lib/aws-codebuild";
import { Secret } from "aws-cdk-lib/aws-secretsmanager";
import {
  CodePipelineSource,
  CodePipeline,
  CodeBuildStep,
  ManualApprovalStep,
  DockerCredential,
  DockerCredentialUsage,
} from "aws-cdk-lib/pipelines";
import { NagSuppressions } from 'cdk-nag';
import { Construct } from "constructs";
import { PipelineConfig } from "./build-config";
import { getConfig } from "./get-config";
import { PipelineAppStage } from "./pipeline-app-stage";

let config: PipelineConfig = getConfig("pipeline");

export class PipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const source = CodePipelineSource.connection(
      config.repoString,
      config.branch,
      {
        connectionArn: config.connectionArn,
      }
    );
    const dockerHubSecret = Secret.fromSecretCompleteArn(
      this,
      "DHSecret",
      config.dockerTokenSecret
    );
    const pipeline = new CodePipeline(this, "EarndStartStopSvcs", {
     ... some code ....
        }),
      }),
    });

   ...more code...
    
    pipeline.buildPipeline();
    NagSuppressions.addResourceSuppressionsByPath(this, '/StartStopSvcsPipelineStack/EarndStartStopSvcs/Pipeline/Role/DefaultPolicy/Resource', [
      {
        id: 'AwsSolutions-IAM5',
        reason: 'Policy created by CDK to allow cross-account access and CB projects rights',
      },
    ]);
  }
}
```
And this is the **path**: 
```
/StartStopSvcsPipelineStack/EarndStartStopSvcs/Pipeline/Role/DefaultPolicy/Resource
```
It is worth mentioning that I am managing two test.ts files: one for my stack (stack.test.ts), which the cdk-nag tests work very well and the one for my pipeline (pipeline.test.ts) which fails because of the aforementioned error.

**Comment by dontirun** [comment]
I think the problem _may_ be with the stack name in the  suppresison

```
    NagSuppressions.addResourceSuppressionsByPath(this, '/StartStopSvcsPipelineStack/EarndStartStopSvcs/Pipeline/Role/DefaultPolicy/Resource', [
      {
        id: 'AwsSolutions-IAM5',
        reason: 'Policy created by CDK to allow cross-account access and CB projects rights',
      },
    ]);
```    

The stack name in your suppression `StartStopSvcsPipelineStack` does not match up with the stack name you used in your tests (`PipelineStack`) this would lead to the construct path being different in your test stack. You could change the suppression path to something like the following to account for varying stack names.
```
 `/{this.stackName}/EarndStartStopSvcs/Pipeline/Role/DefaultPolicy/Resource`
```

**Comment by msaavedra-earnd** [comment]
Yes, that was the problem, thanks a lot for the help, @dontirun!

Also, I think it would be nice to add in the repository, as documentation, how to configure the tests for cdk-nag. I found the information outside the repository but being part of the cdk-nag implementation, I think it would be nice to have it here somewhere or at least a link to the doc.

**Comment by dontirun** [comment]
The unit tests aren't technically part of cdk-nag and  are language specific. That being said, I agree it would be useful to have and documentation in the README to help with it
