### ISSUE TITLE
Unhandled error in `nist80053EC2CheckSSHRestricted` when `cidrIp` is `Fn::GetAtt`

### ISSUE THREAD

**Issue by kylelaker-ccpo** [cdklabs/cdk-nag#388]
We are experience synthesis failure due to an unhandled error during from the NIST SP 800-53 checks; however, this code seems to be partially duplicated between HIPAA and AWS Solutions as well. Specifically, it looks like our [VPC stack](https://github.com/dod-ccpo/atat-web-api/blob/feature/AT-6523/infrastructure/lib/atat-net-stack.ts) currently is the source of the issue and the underlying error is from [`src/NIST-800-53/rules/ec2/nist80053EC2CheckSSHRestricted.ts`](https://github.com/cdklabs/cdk-nag/blob/main/src/NIST-800-53/rules/ec2/nist80053EC2CheckSSHRestricted.ts#L22):

```
/home/klaker/Documents/ccpo/atat-web-api/node_modules/cdk-nag/src/NIST-800-53/rules/ec2/nist80053EC2CheckSSHRestricted.ts:22
            resolvedRule.cidrIp.includes('/0')) ||
                                ^
TypeError: resolvedRule.cidrIp.includes is not a function
    at Object.default_1 (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/cdk-nag/src/NIST-800-53/rules/ec2/nist80053EC2CheckSSHRestricted.ts:22:33)
    at NIST80053Checks.checkEC2 (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/cdk-nag/src/NIST-800-53/nist-800-53.ts:399:8)
    at NIST80053Checks.visit (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/cdk-nag/src/NIST-800-53/nist-800-53.ts:102:12)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:110:14)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at recurse (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at invokeAspects (/home/klaker/Documents/ccpo/atat-web-api/infrastructure/node_modules/@aws-cdk/core/lib/private/synthesis.ts:95:3)
```

This seems to be because in this case `resolvedRule.cidrIp` is an object (not a string), with the value `{ Fn::GetAtt: [ "VpcLogicalId", "CidrBlock" ] }`. Without cdk-nag, the stack synthesizes and deploys without issue; however the relevant snippet from the template seems to be the following; if I just add a `console.log` in to print `resolvedRule.cidrIp`, the value of `CidrIp` seen below is what gets printed.

```
        "SecurityGroupIngress": [
          {
            "CidrIp": {
              "Fn::GetAtt": [
                "AtatVpc28460212",
                "CidrBlock"
              ]
            },
            "Description": {
              "Fn::Join": [
                "",
                [
                  "from ",
                  {
                    "Fn::GetAtt": [
                      "AtatVpc28460212",
                      "CidrBlock"
                    ]
                  },
                  ":443"
                ]
              ]
            },
            "FromPort": 443,
            "IpProtocol": "tcp",
            "ToPort": 443
          }
        ],
```

This was encountered with cdg-nag v0.0.114 as well as 0.0.98 and with CDK v1.124.0 and v1.125.0.

The full output of synthesis (without running cdk-nag) is available as a workflow artifact at https://github.com/dod-ccpo/atat-web-api/suites/3921230865/artifacts/98054835. The workflow run with the error during synthesis is available at https://github.com/dod-ccpo/atat-web-api/runs/3757681913?check_suite_focus=true#step:9:83.

If there's information that'd be useful that I didn't include, I am happy to do so. This library has been super helpful to start building towards compliance with best practices early on!

**Comment by dontirun** [comment]
Thanks for reporting this issue. In TypeScript/JavaSript, the [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) method can  be invoked on any string. However the Intrinsic functions are JSON ( which would cause this error).

This is a fixable error, however do note that `cdk-nag` will not be able to validate values that the intrinsic function references. In this case if the CIDR block that the `Fn::GetAtt` referenced contained a `/0` cdk-nag would not be able to detect it

**Comment by dontirun** [comment]
@maafk What do you think about this? I can think about a few ways to handle this
1. Wrap most of the `.includes()` methods with a `JSON.stringify()` to handle cases with intrinsic functions. While we wouldn't be able to detect data in `Fn::GetAtt` we could still detect potential issues in `Fn::Join`
2. We could wrap calls to specific rules (or even class functions) in a `try..catch` that we instead add a warning to resources where we run into a situation where we encounter an intrinsic function

**Comment by dontirun** [comment]
I'm leaning toward something relating to the latter since equality comparisons can occur with other types like integers as well
