### ISSUE TITLE
bug: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [cdklabs/cdk-nag#499]
### What is the problem?

I tried to synthesize a stack which had some suppressions applied and it failed with:

```
npx cdk synth                                                                                                                                               [ddc7d00]
.../aws/node_modules/cdk-nag/src/nag-suppressions.ts:78
          newSuppressions.unshift(...currentSuppressions.rules_to_suppress);
                          ^
RangeError: Maximum call stack size exceeded
    at Function.addResourceSuppressions (.../aws/node_modules/cdk-nag/src/nag-suppressions.ts:78:27)
    at new Api (.../aws/service/api.ts:22:21)
    at new ServiceStack (.../aws/service/root.ts:29:17)
    at Object.<anonymous> (.../aws/app.ts:56:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (.../aws/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (.../aws/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Subprocess exited with error 1
```

### Reproduction Steps

Apply many supressions to a resource with many children and specify to include children

### What did you expect to happen?

The supressions should be applied

### What actually happened?

The call stack got to big

### cdk-nag version

1.3.2

### Language

Typescript

**Comment by dontirun** [comment]
@matthias-pichler-warrify 
Version `1.3.4` hopefully resolves this issue
